---
blank_issues_enabled: false
contact_links:
  - name: 📃 Documentation Issue
    url: https://github.com/hossein-zare/react-native-dropdown-picker-website
    about: >
      If this library's docs are incorrect or are missing something,
      please file an issue here.
